import type {
  QualityModule,
  InspectionRecord,
  LiftingOperation,
  ISODocument,
  SQMRecord,
  PermitWorkRecord,
  WeldingWorkRecord,
  JSARecord,
  StopCardRecord,
  TrainingModule,
  PreziRecord,
  OnlineTrainingRecord,
  AuditModule,
  AuditRecord,
  ClaimRecord,
  NonConformRecord,
} from "@/types/qhse"

export const qualityModules: QualityModule[] = [
  {
    id: "inspection",
    name: "Inspection",
    description: "Gestão de inspeções de equipamentos e instalações",
    icon: "search",
    path: "/qhse/quality/inspection",
    status: "active",
    category: "quality",
  },
  {
    id: "lifting",
    name: "Lifting",
    description: "Operações de elevação e movimentação de cargas",
    icon: "crane",
    path: "/qhse/quality/lifting",
    status: "active",
    category: "quality",
  },
  {
    id: "iso",
    name: "ISO",
    description: "Documentos e procedimentos ISO",
    icon: "file-text",
    path: "/qhse/quality/iso",
    status: "active",
    category: "quality",
  },
  {
    id: "sqm",
    name: "SQM",
    description: "Supplier Quality Management - Gestão da qualidade de fornecedores",
    icon: "users",
    path: "/qhse/quality/sqm",
    status: "active",
    category: "quality",
  },
]

export const trainingModules: TrainingModule[] = [
  {
    id: "prezi",
    name: "Prezi",
    description: "Apresentações de treinamento",
    icon: "monitor",
    path: "/qhse/training/prezi",
    status: "active",
    category: "training",
  },
  {
    id: "online",
    name: "Online",
    description: "Treinamentos online",
    icon: "graduation-cap",
    path: "/qhse/training/online",
    status: "active",
    category: "training",
  },
]

export const auditModules: AuditModule[] = [
  {
    id: "audit",
    name: "Audit",
    description: "Auditorias internas e externas",
    icon: "file-check",
    path: "/qhse/audit/audit",
    status: "active",
    category: "audit",
  },
  {
    id: "claims",
    name: "Claims",
    description: "Reclamações de clientes e fornecedores",
    icon: "alert-triangle",
    path: "/qhse/audit/claims",
    status: "active",
    category: "audit",
  },
  {
    id: "non-conform",
    name: "Non Conform",
    description: "Não conformidades e ações corretivas",
    icon: "alert-circle",
    path: "/qhse/audit/non-conform",
    status: "active",
    category: "audit",
  },
]

// Mock data generators
export function generateMockInspections(): InspectionRecord[] {
  return [
    {
      id: "1",
      equipmentId: "EQ001",
      equipmentName: "Compressor Principal",
      inspectionType: "routine",
      inspector: "João Silva",
      date: "2024-01-15",
      status: "completed",
      findings: ["Pressão dentro dos parâmetros", "Filtros limpos"],
      recommendations: ["Substituir filtro em 30 dias"],
      nextInspectionDate: "2024-02-15",
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    {
      id: "2",
      equipmentId: "EQ002",
      equipmentName: "Guindaste Torre",
      inspectionType: "preventive",
      inspector: "Maria Santos",
      date: "2024-01-16",
      status: "in-progress",
      findings: ["Cabo de aço com desgaste"],
      recommendations: ["Substituir cabo de aço urgentemente"],
      createdAt: "2024-01-16T09:00:00Z",
      updatedAt: "2024-01-16T11:00:00Z",
    },
  ]
}

export function generateMockLiftingOperations(): LiftingOperation[] {
  return [
    {
      id: "1",
      operationName: "Instalação de Estrutura Metálica",
      location: "Área de Produção A",
      liftingEquipment: "Guindaste 50T",
      operator: "Carlos Mendes",
      supervisor: "Ana Costa",
      plannedDate: "2024-01-20",
      weight: 2500,
      height: 15,
      status: "planned",
      riskAssessment: "Risco médio - condições climáticas favoráveis",
      safetyMeasures: ["Isolamento da área", "Sinalização adequada", "EPIs obrigatórios"],
      createdAt: "2024-01-10T14:00:00Z",
      updatedAt: "2024-01-10T14:00:00Z",
    },
  ]
}

export function generateMockISODocuments(): ISODocument[] {
  return [
    {
      id: "1",
      documentNumber: "ISO-QUA-001",
      title: "Procedimento de Controle de Qualidade",
      version: "2.1",
      category: "procedure",
      department: "Qualidade",
      owner: "Pedro Oliveira",
      approver: "Diretor de Qualidade",
      effectiveDate: "2024-01-01",
      reviewDate: "2024-12-31",
      status: "approved",
      createdAt: "2023-12-15T10:00:00Z",
      updatedAt: "2024-01-01T08:00:00Z",
    },
  ]
}

export function generateMockSQMRecords(): SQMRecord[] {
  return [
    {
      id: "1",
      supplierName: "Fornecedor ABC Ltda",
      supplierCode: "SUP001",
      category: "Matéria Prima",
      evaluationDate: "2024-01-10",
      evaluator: "Equipe de Qualidade",
      overallScore: 85,
      qualityScore: 90,
      deliveryScore: 80,
      serviceScore: 85,
      status: "approved",
      comments: "Fornecedor confiável com boa qualidade de produtos",
      nextEvaluationDate: "2024-07-10",
      createdAt: "2024-01-10T09:00:00Z",
      updatedAt: "2024-01-10T09:00:00Z",
    },
  ]
}

export function generateMockPermitWork(): PermitWorkRecord[] {
  return [
    {
      id: "1",
      permitNumber: "PW-2024-001",
      workDescription: "Soldagem de tubulação principal",
      location: "Área de Produção B",
      requestor: "João Silva",
      approver: "Supervisor HSE",
      startDate: "2024-01-20T08:00:00Z",
      endDate: "2024-01-20T17:00:00Z",
      status: "approved",
      workType: "hot-work",
      hazards: ["Fogo/explosão", "Fumos de soldagem", "Radiação"],
      safetyMeasures: ["Extintor próximo", "Ventilação adequada", "EPIs obrigatórios"],
      isolationRequired: true,
      gasTestRequired: true,
      createdAt: "2024-01-18T10:00:00Z",
      updatedAt: "2024-01-19T14:30:00Z",
    },
    {
      id: "2",
      permitNumber: "PW-2024-002",
      workDescription: "Manutenção em espaço confinado",
      location: "Tanque de Armazenamento 3",
      requestor: "Maria Santos",
      approver: "Supervisor HSE",
      startDate: "2024-01-22T09:00:00Z",
      endDate: "2024-01-22T16:00:00Z",
      status: "pending",
      workType: "confined-space",
      hazards: ["Atmosfera tóxica", "Deficiência de oxigênio", "Engolfamento"],
      safetyMeasures: ["Teste atmosférico", "Vigia externo", "Equipamento de resgate"],
      isolationRequired: true,
      gasTestRequired: true,
      createdAt: "2024-01-19T11:00:00Z",
      updatedAt: "2024-01-19T11:00:00Z",
    },
  ]
}

export function generateMockWeldingWork(): WeldingWorkRecord[] {
  return [
    {
      id: "1",
      workOrderNumber: "WO-2024-001",
      weldingType: "mig",
      welder: "Carlos Mendes",
      welderCertification: "AWS D1.1",
      location: "Oficina de Soldagem",
      material: "Aço Carbono",
      thickness: 12,
      position: "horizontal",
      inspector: "Ana Costa",
      status: "approved",
      preWeldInspection: true,
      postWeldInspection: true,
      testResults: ["Teste visual aprovado", "Teste de penetrante OK"],
      defects: [],
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2024-01-16T15:30:00Z",
    },
  ]
}

export function generateMockJSA(): JSARecord[] {
  return [
    {
      id: "1",
      jsaNumber: "JSA-2024-001",
      jobDescription: "Troca de filtros do sistema de ventilação",
      location: "Sala de Máquinas",
      supervisor: "Pedro Oliveira",
      workers: ["João Silva", "Maria Santos"],
      date: "2024-01-20",
      status: "approved",
      jobSteps: [
        {
          step: "Desligar sistema de ventilação",
          hazards: ["Choque elétrico"],
          controls: ["Bloqueio/etiquetagem", "Teste de ausência de tensão"],
        },
        {
          step: "Remover filtros usados",
          hazards: ["Inalação de poeira", "Cortes"],
          controls: ["Máscara PFF2", "Luvas de proteção"],
        },
      ],
      riskLevel: "medium",
      approvalRequired: true,
      createdAt: "2024-01-18T09:00:00Z",
      updatedAt: "2024-01-19T10:00:00Z",
    },
  ]
}

export function generateMockStopCards(): StopCardRecord[] {
  return [
    {
      id: "1",
      cardNumber: "SC-2024-001",
      reportedBy: "João Silva",
      location: "Área de Produção A",
      dateReported: "2024-01-19T14:30:00Z",
      description: "Vazamento de óleo hidráulico próximo à passarela",
      immediateAction: "Área isolada com cones e fita zebrada",
      category: "unsafe-condition",
      severity: "medium",
      status: "investigating",
      investigator: "Equipe HSE",
      correctiveActions: ["Reparo do vazamento", "Limpeza da área"],
      targetCloseDate: "2024-01-25",
      createdAt: "2024-01-19T14:30:00Z",
      updatedAt: "2024-01-19T15:00:00Z",
    },
  ]
}

export function generateMockPreziRecords(): PreziRecord[] {
  return [
    {
      id: "1",
      presentationId: "PRZ-2024-001",
      title: "Segurança em Trabalhos de Altura",
      topic: "Segurança do Trabalho",
      presenter: "Ana Costa",
      department: "HSE",
      targetAudience: "Operadores de Campo",
      duration: 120,
      scheduledDate: "2024-01-25T09:00:00Z",
      actualDate: "2024-01-25T09:00:00Z",
      location: "Auditório Principal",
      attendees: ["João Silva", "Maria Santos", "Carlos Mendes", "Pedro Oliveira"],
      maxAttendees: 30,
      status: "completed",
      materials: ["Slides PPT", "Vídeos demonstrativos", "Manual de segurança"],
      objectives: [
        "Identificar riscos em trabalhos de altura",
        "Conhecer EPIs adequados",
        "Aplicar procedimentos de segurança",
      ],
      evaluationScore: 4.5,
      feedback: ["Apresentação muito clara", "Exemplos práticos excelentes", "Duração adequada"],
      certificateIssued: true,
      createdAt: "2024-01-20T10:00:00Z",
      updatedAt: "2024-01-25T11:30:00Z",
    },
    {
      id: "2",
      presentationId: "PRZ-2024-002",
      title: "Controle de Qualidade em Soldagem",
      topic: "Qualidade",
      presenter: "Carlos Mendes",
      department: "Quality",
      targetAudience: "Soldadores e Inspetores",
      duration: 90,
      scheduledDate: "2024-01-30T14:00:00Z",
      location: "Sala de Treinamento B",
      attendees: [],
      maxAttendees: 20,
      status: "scheduled",
      materials: ["Apresentação técnica", "Amostras de soldagem", "Normas AWS"],
      objectives: [
        "Compreender critérios de aceitação",
        "Identificar defeitos comuns",
        "Aplicar técnicas de inspeção visual",
      ],
      feedback: [],
      certificateIssued: false,
      createdAt: "2024-01-22T08:00:00Z",
      updatedAt: "2024-01-22T08:00:00Z",
    },
    {
      id: "3",
      presentationId: "PRZ-2024-003",
      title: "Gestão de Resíduos Industriais",
      topic: "Meio Ambiente",
      presenter: "Maria Santos",
      department: "HSE",
      targetAudience: "Supervisores e Operadores",
      duration: 60,
      scheduledDate: "2024-02-05T10:00:00Z",
      location: "Auditório Principal",
      attendees: ["Ana Costa", "Pedro Oliveira"],
      maxAttendees: 25,
      status: "in-progress",
      materials: ["Legislação ambiental", "Procedimentos internos", "Cases de sucesso"],
      objectives: [
        "Conhecer classificação de resíduos",
        "Aplicar procedimentos de segregação",
        "Compreender destinação adequada",
      ],
      feedback: [],
      certificateIssued: false,
      createdAt: "2024-01-28T09:00:00Z",
      updatedAt: "2024-02-05T10:30:00Z",
    },
  ]
}

export function generateMockOnlineTrainingRecords(): OnlineTrainingRecord[] {
  return [
    {
      id: "1",
      courseId: "ONL-2024-001",
      courseName: "Fundamentos de Segurança do Trabalho",
      category: "safety",
      instructor: "Instituto de Segurança",
      duration: 20,
      enrollmentDate: "2024-01-10T08:00:00Z",
      startDate: "2024-01-12T09:00:00Z",
      completionDate: "2024-01-20T16:30:00Z",
      status: "completed",
      progress: 100,
      modules: [
        {
          moduleId: "MOD001",
          moduleName: "Introdução à Segurança",
          duration: 4,
          completed: true,
          score: 85,
        },
        {
          moduleId: "MOD002",
          moduleName: "EPIs e EPCs",
          duration: 6,
          completed: true,
          score: 92,
        },
        {
          moduleId: "MOD003",
          moduleName: "Prevenção de Acidentes",
          duration: 5,
          completed: true,
          score: 88,
        },
        {
          moduleId: "MOD004",
          moduleName: "Primeiros Socorros",
          duration: 5,
          completed: true,
          score: 90,
        },
      ],
      finalScore: 89,
      passingScore: 70,
      attempts: 1,
      maxAttempts: 3,
      certificateUrl: "/certificates/safety-fundamentals-001.pdf",
      expiryDate: "2025-01-20",
      createdAt: "2024-01-10T08:00:00Z",
      updatedAt: "2024-01-20T16:30:00Z",
    },
    {
      id: "2",
      courseId: "ONL-2024-002",
      courseName: "Gestão da Qualidade ISO 9001",
      category: "quality",
      instructor: "Consultoria Quality Pro",
      duration: 30,
      enrollmentDate: "2024-01-15T10:00:00Z",
      startDate: "2024-01-18T08:00:00Z",
      status: "in-progress",
      progress: 65,
      modules: [
        {
          moduleId: "MOD005",
          moduleName: "Princípios da Qualidade",
          duration: 8,
          completed: true,
          score: 87,
        },
        {
          moduleId: "MOD006",
          moduleName: "Requisitos ISO 9001",
          duration: 10,
          completed: true,
          score: 82,
        },
        {
          moduleId: "MOD007",
          moduleName: "Auditoria Interna",
          duration: 7,
          completed: false,
        },
        {
          moduleId: "MOD008",
          moduleName: "Melhoria Contínua",
          duration: 5,
          completed: false,
        },
      ],
      passingScore: 75,
      attempts: 1,
      maxAttempts: 2,
      createdAt: "2024-01-15T10:00:00Z",
      updatedAt: "2024-01-28T14:20:00Z",
    },
    {
      id: "3",
      courseId: "ONL-2024-003",
      courseName: "Liderança e Comunicação",
      category: "soft-skills",
      instructor: "Academia de Liderança",
      duration: 15,
      enrollmentDate: "2024-01-20T09:00:00Z",
      status: "enrolled",
      progress: 0,
      modules: [
        {
          moduleId: "MOD009",
          moduleName: "Estilos de Liderança",
          duration: 5,
          completed: false,
        },
        {
          moduleId: "MOD010",
          moduleName: "Comunicação Eficaz",
          duration: 5,
          completed: false,
        },
        {
          moduleId: "MOD011",
          moduleName: "Gestão de Conflitos",
          duration: 5,
          completed: false,
        },
      ],
      passingScore: 70,
      attempts: 0,
      maxAttempts: 3,
      createdAt: "2024-01-20T09:00:00Z",
      updatedAt: "2024-01-20T09:00:00Z",
    },
  ]
}

export function generateMockAuditRecords(): AuditRecord[] {
  return [
    {
      id: "1",
      auditNumber: "AUD-2024-001",
      auditType: "internal",
      title: "Auditoria Interna ISO 9001",
      scope: "Sistema de Gestão da Qualidade - Processos de Produção",
      department: "Produção",
      leadAuditor: "Ana Costa",
      auditTeam: ["Pedro Oliveira", "Maria Santos"],
      plannedStartDate: "2024-02-01",
      plannedEndDate: "2024-02-03",
      actualStartDate: "2024-02-01",
      actualEndDate: "2024-02-03",
      status: "closed",
      standard: "ISO 9001:2015",
      findings: [
        {
          id: "F001",
          type: "minor",
          clause: "8.5.1",
          description: "Procedimento de controle de produção não atualizado",
          evidence: "Documento PRC-001 versão 1.2 em uso, versão atual é 1.4",
          correctiveAction: "Atualizar procedimento e treinar equipe",
          responsible: "Supervisor de Produção",
          targetDate: "2024-02-15",
          status: "closed",
        },
        {
          id: "F002",
          type: "observation",
          clause: "7.1.5",
          description: "Oportunidade de melhoria no controle de calibração",
          evidence: "Alguns instrumentos próximos ao vencimento da calibração",
          status: "open",
        },
      ],
      overallRating: "satisfactory",
      reportPath: "/reports/audit-2024-001.pdf",
      followUpRequired: true,
      followUpDate: "2024-03-01",
      createdAt: "2024-01-25T10:00:00Z",
      updatedAt: "2024-02-05T16:30:00Z",
    },
    {
      id: "2",
      auditNumber: "AUD-2024-002",
      auditType: "external",
      title: "Auditoria de Certificação ISO 14001",
      scope: "Sistema de Gestão Ambiental",
      department: "HSE",
      leadAuditor: "Auditor Externo - João Pereira",
      auditTeam: ["Auditor Assistente - Carla Silva"],
      plannedStartDate: "2024-02-15",
      plannedEndDate: "2024-02-17",
      status: "planned",
      standard: "ISO 14001:2015",
      findings: [],
      overallRating: "satisfactory",
      followUpRequired: false,
      createdAt: "2024-01-30T09:00:00Z",
      updatedAt: "2024-01-30T09:00:00Z",
    },
    {
      id: "3",
      auditNumber: "AUD-2024-003",
      auditType: "supplier",
      title: "Auditoria de Fornecedor - ABC Ltda",
      scope: "Avaliação do sistema de qualidade do fornecedor",
      department: "Suprimentos",
      leadAuditor: "Carlos Mendes",
      auditTeam: ["Ana Costa"],
      plannedStartDate: "2024-02-20",
      plannedEndDate: "2024-02-21",
      status: "in-progress",
      standard: "Critérios internos de qualificação",
      findings: [
        {
          id: "F003",
          type: "major",
          clause: "Controle de Qualidade",
          description: "Ausência de controle estatístico de processo",
          evidence: "Não foram apresentados gráficos de controle para produtos críticos",
          status: "open",
        },
      ],
      overallRating: "needs-improvement",
      followUpRequired: true,
      createdAt: "2024-02-10T08:00:00Z",
      updatedAt: "2024-02-20T14:00:00Z",
    },
  ]
}

export function generateMockClaimRecords(): ClaimRecord[] {
  return [
    {
      id: "1",
      claimNumber: "CLM-2024-001",
      claimType: "customer",
      title: "Produto com defeito de fabricação",
      description: "Cliente reportou falha prematura em componente após 2 meses de uso",
      reportedBy: "Atendimento ao Cliente",
      reportedDate: "2024-01-25",
      customer: "Cliente XYZ Ltda",
      product: "Componente Mecânico CM-100",
      batchLot: "LOT-2023-1205",
      quantity: 50,
      value: 2500,
      currency: "EUR",
      status: "investigating",
      priority: "high",
      category: "quality",
      investigator: "Equipe de Qualidade",
      rootCause: "Falha no processo de tratamento térmico",
      correctiveActions: [
        "Revisão do processo de tratamento térmico",
        "Treinamento da equipe de produção",
        "Implementação de controle adicional",
      ],
      preventiveActions: ["Auditoria mensal do processo", "Calibração semanal dos equipamentos"],
      resolution: "Substituição do lote defeituoso e implementação de melhorias no processo",
      resolutionDate: "2024-02-10",
      customerSatisfied: true,
      costImpact: 3200,
      createdAt: "2024-01-25T10:00:00Z",
      updatedAt: "2024-02-10T16:30:00Z",
    },
    {
      id: "2",
      claimNumber: "CLM-2024-002",
      claimType: "supplier",
      title: "Atraso na entrega de matéria-prima",
      description: "Fornecedor atrasou entrega em 2 semanas, impactando cronograma de produção",
      reportedBy: "Departamento de Suprimentos",
      reportedDate: "2024-02-01",
      supplier: "Fornecedor ABC Ltda",
      product: "Matéria-prima MP-200",
      quantity: 1000,
      value: 5000,
      currency: "EUR",
      status: "approved",
      priority: "medium",
      category: "delivery",
      investigator: "Gerente de Suprimentos",
      rootCause: "Problemas na cadeia de suprimentos do fornecedor",
      correctiveActions: ["Negociação de compensação financeira", "Estabelecimento de fornecedor backup"],
      preventiveActions: ["Monitoramento semanal de entregas", "Diversificação de fornecedores"],
      resolution: "Compensação de 10% do valor e garantia de pontualidade futura",
      costImpact: 500,
      createdAt: "2024-02-01T09:00:00Z",
      updatedAt: "2024-02-15T14:00:00Z",
    },
    {
      id: "3",
      claimNumber: "CLM-2024-003",
      claimType: "warranty",
      title: "Falha em equipamento sob garantia",
      description: "Equipamento apresentou falha após 6 meses de operação, ainda sob garantia",
      reportedBy: "Manutenção",
      reportedDate: "2024-02-05",
      product: "Motor Elétrico ME-500",
      quantity: 1,
      value: 1200,
      currency: "EUR",
      status: "received",
      priority: "high",
      category: "quality",
      investigator: "Técnico de Manutenção",
      correctiveActions: [],
      preventiveActions: [],
      resolution: "",
      costImpact: 0,
      createdAt: "2024-02-05T11:00:00Z",
      updatedAt: "2024-02-05T11:00:00Z",
    },
  ]
}

export function generateMockNonConformRecords(): NonConformRecord[] {
  return [
    {
      id: "1",
      ncNumber: "NC-2024-001",
      title: "Produto fora de especificação",
      description: "Lote de produtos com dimensões fora da tolerância especificada",
      detectedBy: "Inspetor de Qualidade",
      detectionDate: "2024-01-28",
      location: "Linha de Produção 2",
      department: "Produção",
      process: "Usinagem",
      product: "Peça Usinada PU-150",
      batchLot: "LOT-2024-0128",
      category: "product",
      severity: "major",
      status: "closed",
      source: "process-monitoring",
      rootCauseAnalysis: {
        method: "5-why",
        analysis:
          "Por que o produto está fora de especificação? Porque a máquina estava desregulada. Por que estava desregulada? Porque não foi feita calibração. Por que não foi feita calibração? Porque o cronograma não foi seguido. Por que o cronograma não foi seguido? Porque faltou pessoal. Por que faltou pessoal? Porque não houve planejamento adequado.",
        rootCause: "Falta de planejamento adequado para manutenção preventiva",
      },
      immediateAction: "Segregação do lote não conforme e retrabalho das peças",
      correctiveActions: [
        {
          action: "Implementar cronograma rigoroso de calibração",
          responsible: "Supervisor de Manutenção",
          targetDate: "2024-02-15",
          completionDate: "2024-02-12",
          status: "completed",
        },
        {
          action: "Treinar equipe em procedimentos de calibração",
          responsible: "Gerente de Produção",
          targetDate: "2024-02-20",
          completionDate: "2024-02-18",
          status: "completed",
        },
      ],
      preventiveActions: [
        {
          action: "Implementar sistema de alerta automático para calibrações",
          responsible: "Engenheiro de Processos",
          targetDate: "2024-03-01",
          completionDate: "2024-02-28",
          status: "completed",
        },
      ],
      verificationMethod: "Auditoria de processo e verificação de calibrações",
      verificationDate: "2024-03-05",
      verifiedBy: "Auditor Interno",
      effectiveness: "effective",
      createdAt: "2024-01-28T14:00:00Z",
      updatedAt: "2024-03-05T16:00:00Z",
    },
    {
      id: "2",
      ncNumber: "NC-2024-002",
      title: "Procedimento não seguido",
      description: "Operador não seguiu procedimento de segurança durante operação de soldagem",
      detectedBy: "Supervisor de Segurança",
      detectionDate: "2024-02-02",
      location: "Oficina de Soldagem",
      department: "Produção",
      process: "Soldagem",
      category: "process",
      severity: "minor",
      status: "corrective-action",
      source: "internal-audit",
      rootCauseAnalysis: {
        method: "fishbone",
        analysis:
          "Análise de causa raiz usando diagrama de Ishikawa identificou fatores relacionados a pessoas (falta de treinamento), método (procedimento não claro), meio ambiente (pressão de prazo) e medição (falta de supervisão adequada)",
        rootCause: "Procedimento de segurança não suficientemente claro e falta de supervisão",
      },
      immediateAction: "Interrupção da atividade e orientação imediata ao operador",
      correctiveActions: [
        {
          action: "Revisar e clarificar procedimento de segurança",
          responsible: "Engenheiro de Segurança",
          targetDate: "2024-02-20",
          status: "in-progress",
        },
        {
          action: "Retreinar todos os soldadores",
          responsible: "Supervisor de Produção",
          targetDate: "2024-02-25",
          status: "planned",
        },
      ],
      preventiveActions: [
        {
          action: "Implementar checklist de segurança obrigatório",
          responsible: "Coordenador HSE",
          targetDate: "2024-03-01",
          status: "planned",
        },
      ],
      verificationMethod: "Observação direta e auditoria comportamental",
      effectiveness: "pending",
      createdAt: "2024-02-02T10:30:00Z",
      updatedAt: "2024-02-15T09:00:00Z",
    },
    {
      id: "3",
      ncNumber: "NC-2024-003",
      title: "Documentação desatualizada",
      description: "Manual de operação encontrado desatualizado na estação de trabalho",
      detectedBy: "Auditor Interno",
      detectionDate: "2024-02-08",
      location: "Estação de Trabalho 5",
      department: "Qualidade",
      process: "Controle de Documentos",
      category: "documentation",
      severity: "minor",
      status: "open",
      source: "internal-audit",
      rootCauseAnalysis: {
        method: "other",
        analysis: "Análise preliminar indica falha no processo de distribuição de documentos atualizados",
        rootCause: "Sistema de controle de documentos não eficaz",
      },
      immediateAction: "Substituição imediata do documento desatualizado",
      correctiveActions: [
        {
          action: "Verificar todas as estações de trabalho",
          responsible: "Analista de Qualidade",
          targetDate: "2024-02-22",
          status: "planned",
        },
      ],
      preventiveActions: [],
      verificationMethod: "Auditoria de controle de documentos",
      effectiveness: "pending",
      createdAt: "2024-02-08T15:00:00Z",
      updatedAt: "2024-02-08T15:00:00Z",
    },
  ]
}

export const mockPreziRecords = generateMockPreziRecords()
export const mockOnlineTrainingRecords = generateMockOnlineTrainingRecords()

export const mockAuditRecords = generateMockAuditRecords()
export const mockClaimRecords = generateMockClaimRecords()
export const mockNonConformRecords = generateMockNonConformRecords()
